<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems><LangVersion>8.0</LangVersion></PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../../Assets/DronePhysics/Core/*.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <Content Include="../../Assets/DronePhysics/Resources/DronePhysics/**/*" Exclude="../../Assets/DronePhysics/Resources/DronePhysics/**/*.meta" Link="Profiles/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
