// Generated by Tools/generate_physics_contract.py. Edit the generator.
using System;

namespace DroneLab.Physics
{
    [Serializable]
    public sealed class Metadata
    {
        public string name;
        public string manufacturer;
        public string model;
        public string description;
    }

    [Serializable]
    public sealed class CoordinateSystem
    {
        public string convention;
        public string lengthUnit;
        public double modelScaleMetersPerUnit;
    }

    [Serializable]
    public sealed class PhysicsModulesProfile
    {
        public bool motorResponse;
        public bool bodyDrag;
        public bool windInteraction;
        public bool groundEffect;
        public bool rotorAerodynamics;
        public bool bladeFlapping;
        public bool inducedDrag;
        public bool batteryDischarge;
        public bool batteryVoltageSag;
        public bool motorElectrical;
        public bool gyroscopicRotorEffects;
    }

    [Serializable]
    public sealed class PhysicsConfiguration
    {
        public string fidelity;
        public PhysicsModulesProfile modules;
    }

    [Serializable]
    public sealed class InertiaProfile
    {
        public string mode;
        public double[] principalMomentsKgM2;
        public double[] principalAxesRotationXyzw;
    }

    [Serializable]
    public sealed class MassProperties
    {
        public double massKg;
        public double[] centerOfMassLocalM;
        public double[] dimensionsM;
        public InertiaProfile inertia;
    }

    [Serializable]
    public sealed class EfficiencyPoint
    {
        public double loadFraction;
        public double efficiency;
    }

    [Serializable]
    public sealed class MotorElectricalProfile
    {
        public double motorKvRpmPerVolt;
        public double motorResistanceOhm;
        public double noLoadCurrentA;
        public double maxCurrentA;
        public double maxPowerW;
        public double motorEfficiency;
        public EfficiencyPoint[] efficiencyCurve;
        public double escEfficiency;
        public double escMaxCurrentA;
    }

    [Serializable]
    public sealed class MotorProfile
    {
        public double minRpm;
        public double idleRpm;
        public double maxRpm;
        public double responseTimeUpS;
        public double responseTimeDownS;
        public double rotatingInertiaKgM2;
        public MotorElectricalProfile electrical;
    }

    [Serializable]
    public sealed class PropellerProfile
    {
        public double diameterM;
        public double pitchM;
        public int bladeCount;
    }

    [Serializable]
    public sealed class RpmPerformancePoint
    {
        public double rpm;
        public double thrustN;
        public double torqueNm;
        public double currentA;
    }

    [Serializable]
    public sealed class PerformanceMapPoint
    {
        public double rpm;
        public double advanceRatio;
        public double ct;
        public double cq;
        public double reynolds;
    }

    [Serializable]
    public sealed class RotorPerformanceProfile
    {
        public string model;
        public double kThrustNPerRadPerSecSquared;
        public double kTorqueNmPerRadPerSecSquared;
        public double referenceAirDensityKgM3;
        public double ct;
        public double cq;
        public RpmPerformancePoint[] rpmTable;
        public PerformanceMapPoint[] performanceMap;
        public string outOfRangePolicy;
    }

    [Serializable]
    public sealed class RotorGeometry
    {
        public double[] positionLocalM;
        public double[] thrustAxisLocal;
        public string spinDirection;
    }

    [Serializable]
    public sealed class RotorAerodynamicsProfile
    {
        public double rotorDragCoefficientKgPerRad;
        public double bladeFlappingCoefficient;
        public double inducedDragCoefficient;
    }

    [Serializable]
    public sealed class RotorProfile
    {
        public string rotorId;
        public RotorGeometry geometry;
        public MotorProfile motor;
        public PropellerProfile propeller;
        public RotorPerformanceProfile performance;
        public RotorAerodynamicsProfile advancedAerodynamics;
    }

    [Serializable]
    public sealed class ProjectedAreaSample
    {
        public double[] directionLocal;
        public double areaM2;
    }

    [Serializable]
    public sealed class ProjectedAreaProfile
    {
        public string mode;
        public ProjectedAreaSample[] samples;
        public double[] referenceAreaM2;
    }

    [Serializable]
    public sealed class AeroSurfaceProfile
    {
        public string surfaceId;
        public double[] positionLocalM;
        public double[] normalLocal;
        public double areaM2;
        public double dragCoefficient;
    }

    [Serializable]
    public sealed class BodyAerodynamicsProfile
    {
        public string model;
        public double[] dragCd;
        public double[] referenceAreaM2;
        public double dragCoefficient;
        public ProjectedAreaProfile projectedArea;
        public double[] dragApplicationPointLocalM;
        public AeroSurfaceProfile[] surfaces;
    }

    [Serializable]
    public sealed class GroundEffectProfile
    {
        public double coefficient;
        public double minHeightRadiusRatio;
        public double maxMultiplier;
    }

    [Serializable]
    public sealed class OcvPoint
    {
        public double soc;
        public double voltageV;
    }

    [Serializable]
    public sealed class BatteryProfile
    {
        public string mode;
        public int cellCount;
        public double nominalVoltageV;
        public double capacityAh;
        public double initialSoc;
        public double internalResistanceOhm;
        public double maxDischargeCurrentA;
        public OcvPoint[] ocvCurve;
    }

    [Serializable]
    public sealed class PowerSystemProfile
    {
        public BatteryProfile battery;
    }

    [Serializable]
    public sealed class DerivedProfile
    {
        public ProjectedAreaSample[] projectedAreaLut;
        public double hoverRpm;
        public double maxTotalThrustN;
        public double thrustToWeightRatio;
        public double[] rotorDiskAreasM2;
        public double[] approximateInertiaKgM2;
    }

    [Serializable]
    public sealed class ParameterProvenance
    {
        public string path;
        public string sourceType;
        public string source;
        public double confidence;
    }

    [Serializable]
    public sealed class DroneProfile
    {
        public string schemaVersion;
        public Metadata metadata;
        public CoordinateSystem coordinateSystem;
        public PhysicsConfiguration physicsConfiguration;
        public MassProperties massProperties;
        public RotorProfile[] rotors;
        public BodyAerodynamicsProfile bodyAerodynamics;
        public GroundEffectProfile groundEffect;
        public PowerSystemProfile powerSystem;
        public DerivedProfile derived;
        public ParameterProvenance[] parameterProvenance;
    }

    [Serializable]
    public sealed class EnvironmentProfile
    {
        public string schemaVersion;
        public double gravityMps2;
        public string airDensityMode;
        public double airDensityKgM3;
        public double temperatureK;
        public double pressurePa;
        public double altitudeM;
        public string windMode;
        public double[] windVelocityWorldMps;
        public bool gustEnabled;
        public double gustIntensityMps;
        public double gustTimeScaleS;
        public int turbulenceSeed;
    }

}
